name: Inspire Oman
seoTitle: Inspire Oman - Telling Oman's Growth Story Globally
seoDescription: >-
  A prestigious integrated initiative aligned with Oman Vision 2040. Investors
  Summit - 11 October 2026, Oman Convention & Exhibition Centre.
slogan: Celebrating Success. Creating Legacy. Inspiring Investment.
description: >-
  A prestigious integrated initiative aligned with Oman Vision 2040, celebrating
  contributions of Oman's business community and enabling future collaborations.
summitDate: 11 October 2026
venue: Oman Convention & Exhibition Centre
city: Muscat
